name: "Archive and Slack: NYTimes"

on:
  schedule:
    - cron: "5 10,16,22 * * *"
  workflow_dispatch:

jobs:
  archive-site:
    name: Archive NYTimes
    uses: ./.github/workflows/reusable-archive-single-site-workflow.yml
    with:
      handle: nytimes
    secrets: inherit

  slack:
    name: Post to Slack
    runs-on: ubuntu-latest
    needs: [archive-site]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/slack
        with:
          handle: nytimes
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_NYTIMES }}
