name: "Archive and Slack: Washington Post"

on:
  schedule:
    - cron: "10 10,16,22 * * *"
  workflow_dispatch:

jobs:
  archive-site:
    name: Archive Washington Post
    uses: ./.github/workflows/reusable-archive-single-site-workflow.yml
    with:
      handle: washingtonpost
    secrets: inherit

  slack:
    name: Post to Slack
    runs-on: ubuntu-latest
    needs: [archive-site]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/slack
        with:
          handle: washingtonpost
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_WASHINGTONPOST }}
